services:
  frontend-dev:
    image: node:lts
    working_dir: /app
    container_name: frontend-dev
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - strapi
    networks:
      - dev-network
    restart: unless-stopped

  strapi:
    image: node:22-alpine
    restart: unless-stopped
    working_dir: /srv/app
    command: sh -c "npm install && npm run develop"
    env_file:
      - ./cms/.env.dev
    volumes:
      - ./cms:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    networks:
      - dev-network

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

  webhook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.webhook
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./frontend/.env.dev
    environment:
      - WEBHOOK_PORT=9000
      - REBUILD_COMMAND=docker exec frontend-dev /app/rebuild.sh --no-nginx
    networks:
      - dev-network
    depends_on:
      - strapi

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-data:
