networks:
  pofys-network:
    driver: bridge

services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.keys:/etc/nginx/.keys:ro
    networks:
      - pofys-network
    depends_on:
      - frontend
      - strapi
      - webhook
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - ./frontend/nginx/frontend.nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - strapi
    networks:
      - pofys-network
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "mkdir -p /app/dist &&
             rm -f /etc/nginx/conf.d/default.conf &&
             nginx -g 'daemon off;'"

  strapi:
    image: node:22-alpine
    restart: unless-stopped
    working_dir: /srv/app
    command: sh -c "npm install && npm run build && npm run start"
    # command: sh -c "npm install && npm run develop"
    env_file:
      - ./cms/.env
    volumes:
      - ./cms:/srv/app
      - strapi-uploads:/srv/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    networks:
      - pofys-network

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - ./cms/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pofys-network

  webhook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.webhook
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_PORT=9000
      - REBUILD_COMMAND=docker exec frontend /app/rebuild.sh
    networks:
      - pofys-network
    depends_on:
      - frontend

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile.tor
    volumes:
      - tor-data:/var/lib/tor/hidden_service/
    networks:
      - pofys-network
    restart: unless-stopped

volumes:
  postgres-data:
  strapi-uploads:
  tor-data:
