name: Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy .env files
        run: |
          cp frontend/.env.example frontend/.env
          cp cms/.env.example cms/.env

      - name: Build
        run: docker compose -f docker-compose.dev.yml build

      - name: Down
        run: docker compose -f docker-compose.dev.yml down -v --remove-orphans

      - name: Up
        run: docker compose -f docker-compose.dev.yml up -d

      - name: Show container status
        if: always()
        run: docker compose -f docker-compose.dev.yml ps -a

      - name: Show logs on failure
        if: failure()
        run: docker compose -f docker-compose.dev.yml logs

      - name: Down
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v --remove-orphans